setwd("~/MATLAB/Paper/27-Nov-2017")
A_data = read.csv("A_hist_data.csv", header = FALSE)
A_data$V1 <- factor(A_data$V1)
B_data = read.csv("B_hist_data.csv", header = FALSE)
B_data$V1 <- factor(B_data$V1)
C_data = read.csv("C_hist_data.csv", header = FALSE)
C_data$V1 <- factor(C_data$V1)
D_data = read.csv("D_hist_data.csv", header = FALSE)
D_data$V1 <- factor(D_data$V1)
